language: android
jdk: oraclejdk8
env:
    matrix:
        - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25
    - sys-img-armeabi-v7a-android-21

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - pip install --user codecov    #Install codecov

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
 - chmod +x gradlew
 - android list targets
 - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
 - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
  - android-wait-for-emulator
  - adb devices   #Display list of devices
  - adb shell input keyevent 82 &
  - ./gradlew check

after_success:
    - codecov                       #Run codecov
