language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

before_script:
 - chmod +x gradlew

script:
  - ./gradlew check
