sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-22
    - build-tools-25.0.1
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-22

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - pip install --user codecov

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82
  - adb shell am start -a android.intent.action.MAIN -n com.android.settings/.Settings\"\$\"DataUsageSummaryActivity
  - adb shell input keyevent 20
  - adb shell input keyevent 20
  - adb shell input keyevent 23

script:
  - ./gradlew check
  
after_success:
  - codecov

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle